### ISSUE TITLE
Redirect hls-app.now.sh to hls.nsfc.live

### ISSUE THREAD

**Issue by ninest** [HavenOfExcellence/hls-soundboard-web#2]
Vercel has the option to set redirects

**Comment by francisyzy** [comment]
Its okay. We leave two variants running for now coz uh NSFC.LIVE will expire one day

**Comment by ninest** [comment]
Oh, is nsfc.live someone's or your free domain?

**Comment by francisyzy** [comment]
It's from my GitHub edu thingy.
